# Generated by Django 3.0.5 on 2020-04-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=5)),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField(max_length=20)),
                ('smoking_history', models.CharField(choices=[('N', 'Never Smoked'), ('F', 'Former Smoker'), ('C', 'Current Smoker')], max_length=20)),
                ('chronic_opd', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('diabetes', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('hypertension', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('coronary_hd', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('cerebrovascular', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('hepatitis_b', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('cancer', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('chronic_renal', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('immunodeficiency', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('screening_test', models.CharField(choices=[('y', 'yes'), ('n', 'no')], max_length=10)),
                ('current_location', models.CharField(max_length=20)),
                ('current_postalcode', models.IntegerField(max_length=20)),
                ('height', models.IntegerField(max_length=20)),
                ('weight', models.IntegerField(max_length=20)),
                ('temperature', models.IntegerField(max_length=20)),
            ],
        ),
    ]
